esphome:
  name: esphome-test
  # min_version: 2024.11.0
  name_add_mac_suffix: false
  platformio_options:
    board_build.f_cpu: 160000000L #increase clock speed

esp8266:
  board: d1_mini  # Adjust to your specific ESP8266 board

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_pass

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  ap:
    ssid: "FTD Fallback"
    password: !secret fallback_password

captive_portal:

logger:
  level: DEBUG
  baud_rate: 9600

web_server:
  version: 3